[package]
name = "qchem_g16"
version = "0.2.1"
authors = ["Cyrille Lavigne <clavigne@chem.utoronto.ca>"]
edition = "2018"

[lib]
name = "qchem_g16"
path = "src/lib.rs"

[dependencies]
clap = "3.0.0-beta.2"
anyhow = "1.0"

